name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # 仅在 tag push 时触发
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag and check if latest
        id: version_check
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          if echo "$TAG_NAME" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "IS_LATEST=true" >> $GITHUB_ENV
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "IS_LATEST=false" >> $GITHUB_ENV
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image (with or without latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            likeflyme/cloudbak:${{ env.TAG_NAME }}
            ${{ steps.version_check.outputs.is_latest == 'true' && 'likeflyme/cloudbak:latest' || '' }}
          build-args: |
            SYSTEM_VERSION=${{ env.TAG_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
