name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # 仅在 tag push 时触发
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - name: Extract Tag Name and Determine Latest
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          # 检查是否是类似 1.2.3 的版本（不带后缀）
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "IS_LATEST=true" >> $GITHUB_ENV
          else
            echo "IS_LATEST=false" >> $GITHUB_ENV
          fi

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image (With or Without latest)
        run: |
          TAGS="likeflyme/cloudbak:${TAG_NAME}"
          if [[ "$IS_LATEST" == "true" ]]; then
            TAGS="$TAGS,likeflyme/cloudbak:latest"
          fi

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --build-arg SYSTEM_VERSION=$TAG_NAME \
            --tag $TAGS \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .
